name: Auto Labeler

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  update_pr_labels:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
